#!/usr/bin/env bash
# Script to install nginx web server,configure ti isten to port 80

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
