#!/usr/bin/env bash
# Script prinitng contents of the file `/etc/passwd`.
#   just printing username, user id, user Home directory path

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
