#!/usr/bin/env bash
# Script to print time for 12 horus and 59 minutes.
#   prints hours from 0 to 12
#   prints minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
