#!/usr/bin/env bash
# Client configuration for ssh.
Host *
    PasswordAuthentication no
    IdentifyFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
